// frontend/components/app/ImageUploader.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CropIcon, RotateCcwIcon, UploadCloudIcon, XIcon } from "lucide-react";
import Image from "next/image";
import {
  type ChangeEvent,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import { ImageCrop } from "../ui/shadcn-io/image-crop";
import { ImageCropApply } from "../ui/shadcn-io/image-crop/image-crop-apply";
import { ImageCropContent } from "../ui/shadcn-io/image-crop/image-crop-content";
import { ImageCropReset } from "../ui/shadcn-io/image-crop/image-crop-reset";
import { Image as ImageIcon } from "@mynaui/icons-react";
import { useMediaQuery } from "react-responsive";
import { cn } from "@/lib/utils";
import { useRecogniserStore } from "@/lib/stores";
import { useMutation } from "@tanstack/react-query";
import { apiIdentifiedActorsType } from "@/lib/schemas";

const ImageUploader = () => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [croppedImage, setCroppedImage] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [pasteError, setPasteError] = useState<string | null>(null);
  const isTouch = useMediaQuery({ query: "(hover: none)" });

  const fileInputRef = useRef<HTMLInputElement>(null);

  const {
    isUploading,
    setIsUploading,
    setIdentifiedActors,
    setSelectedActorId,
  } = useRecogniserStore();

  const identifyMutation = useMutation({
    mutationFn: async (formData: FormData) => {
      const res = await fetch("/api/identify", {
        method: "POST",
        body: formData,
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || "Something went wrong");
      }

      return res.json();
    },
    onSuccess: (data) => {
      const formattedMatches = data.matches.map(
        (match: apiIdentifiedActorsType) => ({
          ...match,
          matchConfidence: match.match_confidence,
          imageUrl: match.image_url,
        })
      );
      setIdentifiedActors(formattedMatches);
      setIsUploading(false);
    },
    onError: (error) => {
      console.error("Upload failed:", error);
      setIsUploading(false);
      setIdentifiedActors(null);
    },
  });

  useEffect(() => {
    document.onpaste = function (event) {
      const items = event.clipboardData?.items;

      if (!items) {
        setPasteError("No image found in clipboard");
        setTimeout(() => setPasteError(null), 2000);
        return;
      }

      for (const item of items) {
        if (item.kind === "file") {
          const file = item.getAsFile();

          if (file && file.type.startsWith("image/")) {
            setSelectedFile(file);
            return;
          }
        }
      }

      if (!selectedFile) {
        setPasteError("No image found in clipboard");
        setTimeout(() => setPasteError(null), 2000);
      }
    };
    return () => {
      document.onpaste = null;
    };
  }, []);

  const handlePaste = async () => {
    try {
      const clipboardItems = await navigator.clipboard.read();
      for (const item of clipboardItems) {
        if (
          item.types.includes("image/png") ||
          item.types.some((type) => type.startsWith("image/"))
        ) {
          const blob = await item.getType("image/png");
          if (blob) {
            const file = new File([blob], "pasted-image.png", {
              type: blob.type,
            });

            setSelectedFile(file);
            return;
          }
        }
      }
      setPasteError("No image found in clipboard");
      setTimeout(() => setPasteError(null), 2000);
    } catch (error) {
      console.error("Failed to read clipboard contents:", error);
      alert(
        "Permission to read the clipboard was denied or no image was found."
      );
    }
  };

  const handleUpload = async () => {
    if (croppedImage) {
      setIsUploading(true);
      const res = await fetch(croppedImage);
      const blob = await res.blob();
      const file = new File([blob], "cropped_image.png", { type: "image/png" });
      const formData = new FormData();
      formData.append("image", file);

      identifyMutation.mutate(formData);
    }
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  };

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      setCroppedImage(null);
    }
  };

  const handleDrop = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    const file = e.dataTransfer.files?.[0];
    if (file && file.type.startsWith("image/")) {
      const event = {
        target: {
          files: [file],
        },
      } as unknown as React.ChangeEvent<HTMLInputElement>;
      handleFileChange(event);
    }
  }, []);

  const handleReset = () => {
    setIdentifiedActors(null);
    setSelectedActorId(null);
    setSelectedFile(null);
    setCroppedImage(null);
    setIsUploading(false);
  };

  if (!selectedFile) {
    return (
      <div className="gap-8 lg:gap-16 w-full mb-6">
        <div className="items-start space-y-2">
          <Input
            accept="image/*"
            type="file"
            id="image-upload"
            onChange={handleFileChange}
            className="hidden"
            ref={fileInputRef}
          />
          <div
            onDragOver={handleDragOver}
            onDragEnter={handleDragEnter}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={cn(
              "h-64 cursor-pointer gap-4 rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 transition-colors hover:bg-muted",
              isDragging && "border-primary/50 bg-primary/5"
            )}
          >
            <label
              htmlFor="image-upload"
              className="flex-center flex-col h-full"
            >
              <div className="rounded-full bg-background p-3 shadow-sm">
                <ImageIcon className="h-6 w-6 text-muted-foreground" />
              </div>
              <div className="text-center">
                <p className="text-sm font-bold font-proxima">
                  {isTouch ? "Tap" : "Click"} to upload
                </p>
                <p className="text-xs text-muted-foreground font-proxima">
                  or paste/drag the file here
                </p>
              </div>
            </label>

            <div onClick={handlePaste}>
              <p className="text-xs text-muted-foreground font-proxima place-self-center mt-4">
                or{" "}
                <span className="font-bold underline">
                  {isTouch ? "tap" : "click"} here
                </span>{" "}
                to upload from clipboard
              </p>
            </div>
            {pasteError && (
              <p className="text-xs text-red-500 font-proxima place-self-center mt-2">
                {pasteError}
              </p>
            )}
          </div>
        </div>
      </div>
    );
  }
  if (!croppedImage) {
    return (
      <div className="space-y-4">
        <ImageCrop
          aspect={1}
          file={selectedFile}
          maxImageSize={1024 * 1024 * 3} // 3MB
          onCrop={setCroppedImage}
        >
          <ImageCropContent className="max-w-md" />
          <div className="grid grid-cols-11 gap-2">
            <Button
              onClick={handleReset}
              size="icon"
              type="button"
              variant="outline"
              className="w-full col-span-5 sm:col-span-3"
            >
              <XIcon className="size-4" />
              <p className="text-xs">Cancel</p>
            </Button>
            <ImageCropReset className="col-span-6 sm:col-span-4 w-full">
              <RotateCcwIcon />
              <p className="text-xs">Reset</p>
            </ImageCropReset>
            <ImageCropApply
              className="col-span-11 sm:col-span-4 w-full"
              asChild
            >
              <Button
                onClick={handleUpload}
                size="icon"
                type="button"
                variant="default"
                className="w-full col-span-11 sm:col-span-4"
                disabled={isUploading}
              >
                <CropIcon />
                <p className="text-xs">Crop</p>
              </Button>
            </ImageCropApply>
          </div>
        </ImageCrop>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <Image
        alt="Cropped"
        height={350}
        src={croppedImage}
        unoptimized
        width={350}
      />
      <div className="grid grid-cols-5 gap-4">
        <Button
          onClick={handleReset}
          size="icon"
          type="button"
          variant="outline"
          className="w-full col-span-2"
          disabled={isUploading}
        >
          <XIcon className="size-4" />
        </Button>
        <Button
          onClick={handleUpload}
          size="icon"
          type="button"
          variant="default"
          className="w-full col-span-3"
          disabled={isUploading}
        >
          {isUploading ? (
            <p>Uploading...</p>
          ) : (
            <UploadCloudIcon className="size-4" />
          )}
          <p className="text-xs">{isUploading ? "" : "Use image"}</p>
        </Button>
        {identifyMutation.isError && (
          <p className="text-sm text-red-500 col-span-5 text-center">
            Upload failed: {identifyMutation.error.message}
          </p>
        )}
      </div>
    </div>
  );
};

export default ImageUploader;

// frontend/src/components/ImageUploader.vue
<template>
  <div class="image-uploader">
    <label for="image-input" class="visually-hidden">Upload Image</label>
    <input
      id="image-input"
      type="file"
      accept="image/*"
      @change="onFileChange"
      ref="fileInput"
      style="display: none"
    />
    <div
      class="drop-area"
      tabindex="0"
      @paste="onPaste"
      @dragover.prevent
      @drop.prevent="onDrop"
      @click="triggerFileInput"
    >
      <span>Click to upload an image or paste an image here</span>
    </div>
    <div v-if="imageUrl" class="cropper-area">
      <Cropper
        ref="cropperRef"
        :src="imageUrl"
        :stencil-props="{ aspectRatio: 1 }"
        :auto-zoom="true"
        :resize-image="true"
        class="cropper"
        @change="onCrop"
      />
    </div>
    <div v-if="croppedImage" class="preview">
      <img :src="croppedImage" alt="Cropped Preview" />
    </div>
    <button v-if="croppedImage && !loading" class="submit-btn" type="button" @click="onSubmit">
      Submit
    </button>
    <div v-if="loading" class="loading">Submitting...</div>
    <div v-if="error" class="error">{{ error }}</div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Cropper } from 'vue-advanced-cropper'
import 'vue-advanced-cropper/dist/style.css'
import type { ActorMatchesResponse } from '../types'

const emit = defineEmits<{
  'actor-identified': [result: ActorMatchesResponse]
}>()

const imageUrl = ref<string | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const cropperRef = ref<any>(null)
const croppedImage = ref<string | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)

function triggerFileInput() {
  fileInput.value?.click()
}

function onFileChange(event: Event) {
  const files = (event.target as HTMLInputElement).files
  if (files && files[0]) {
    const file = files[0]
    if (file.type.startsWith('image/')) {
      imageUrl.value = URL.createObjectURL(file)
      croppedImage.value = null
      error.value = null
    }
  }
}

function onPaste(event: ClipboardEvent) {
  const items = event.clipboardData?.items
  if (!items) return
  for (const item of items) {
    if (item.type.startsWith('image/')) {
      const file = item.getAsFile()
      if (file) {
        imageUrl.value = URL.createObjectURL(file)
        croppedImage.value = null
        error.value = null
        break
      }
    }
  }
}

function onDrop(event: DragEvent) {
  const files = event.dataTransfer?.files
  if (files && files[0] && files[0].type.startsWith('image/')) {
    imageUrl.value = URL.createObjectURL(files[0])
    croppedImage.value = null
    error.value = null
  }
}

function onCrop() {
  if (cropperRef.value) {
    const canvas = cropperRef.value.getResult().canvas
    if (canvas) {
      croppedImage.value = canvas.toDataURL('image/png')
    }
  }
}

async function onSubmit() {
  error.value = null
  loading.value = true
  try {
    if (!croppedImage.value) return
    const res = await fetch(croppedImage.value)
    const blob = await res.blob()
    const formData = new FormData()
    formData.append('image', blob, 'image.png')
    const response = await fetch('http://localhost:8080/identify-actor', {
      method: 'POST',
      body: formData,
    })
    if (!response.ok) {
      throw new Error('Failed to identify actor')
    }
    const data = await response.json()
    emit('actor-identified', data)
  } catch (e: any) {
    error.value = e.message || 'Unknown error'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.drop-area {
  border: 2px dashed #aaa;
  border-radius: 8px;
  padding: 1.5rem 2rem;
  text-align: center;
  color: #888;
  min-width: 250px;
  outline: none;
  cursor: pointer;
}
.drop-area:focus {
  border-color: #333;
}
.preview img {
  max-width: 300px;
  max-height: 300px;
  margin-top: 1rem;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
}
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
.submit-btn {
  margin-top: 1.5rem;
  padding: 0.75rem 2rem;
  font-size: 1.1rem;
  font-weight: 600;
  color: #fff;
  background: #0078d4;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background 0.2s;
}
.submit-btn:hover {
  background: #005fa3;
}
.cropper-area {
  width: 320px;
  height: 320px;
  margin-top: 1.5rem;
  background: #f8f8f8;
  border-radius: 8px;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}
.cropper {
  width: 300px;
  height: 300px;
}
.loading {
  margin-top: 1rem;
  color: #0078d4;
  font-weight: 500;
}
.error {
  margin-top: 1rem;
  color: #d40000;
  font-weight: 500;
}
</style>
